# Generated by Django 5.2.4 on 2025-07-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('h1', models.IntegerField(default=0)),
                ('h2', models.IntegerField(default=0)),
                ('title', models.IntegerField(default=0)),
                ('meta_title', models.IntegerField(default=0)),
                ('meta_description', models.IntegerField(default=0)),
                ('og_title', models.IntegerField(default=0)),
                ('og_description', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
