# Generated by Django 5.2.4 on 2025-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
